## Question 1
The LU decomposition with row pivoting of the matrix

$$
A=\left(\begin{array}{cccc}
2 & -1 & 0 & 1 \\
-2 & 0 & 1 & -1 \\
4 & -1 & 0 & 1 \\
4 & -3 & 0 & 2
\end{array}\right)
$$


is given by $P A=L U$, where

$$
P=\left(\begin{array}{cccc}
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
0 & 1 & 0 & 0 \\
1 & 0 & 0 & 0
\end{array}\right) ; \quad L=\left(\begin{array}{cccc}
1 & 0 & 0 & 0 \\
1 & 1 & 0 & 0 \\
-0.5 & 0.25 & 1 & 0 \\
0.5 & 0.25 & 0 & 1
\end{array}\right) ; \quad U=\left(\begin{array}{cccc}
4 & -1 & 0 & 1 \\
0 & -2 & 0 & 1 \\
0 & 0 & 1 & -0.75 \\
0 & 0 & 0 & 0.25
\end{array}\right)
$$

(i) Solve $A x=b$, where

$$
b=\left(\begin{array}{c}
3 \\
-1 \\
0 \\
2
\end{array}\right)
$$

(ii) Find $A^{-1}$, the inverse matrix of $A$.


## Question 2
The following discount factors are obtained by fitting market data:

$$
\begin{array}{cc}
\text{Date} & \text{Discount Factor} \\
2 \text{ months} & 0.9980 \\
5 \text{ months} & 0.9935 \\
11 \text{ months} & 0.9820 \\
15 \text{ months} & 0.9775 \\
\end{array}
$$

The overnight rate is 1%.

(i) What is the linear system that has to be solved for the cubic spline interpolation of the zero rate curve?


(ii) Use cubic spline interpolation to find a zero rate curve for all times less than 15 months matching the discount factors above.                

(iii) Find the value of a 13 months quarterly bond with $2.5 \%$ coupon rate.

Note: A quarterly coupon bond with face value $\$ 100$, coupon rate $C$, and maturity $T$ pays the holder of the bond a coupon payment equal to $\frac{C}{4} \cdot 100$ every three months, except at maturity. The final payment at maturity $T$ is equal to the face value of the bond plus one coupon payment, i.e., $100+\frac{C}{4} 100$.

## Question 3
The values of the following coupon bonds with face value $\$ 100$ are given:

$$
\begin{array}{lcl}
\text{Bond Type} & \text{Coupon Rate} & \text{Bond Price} \\
\text{10 months semiannual} & \text{3\%} & \$ 101.30 \\
\text{16 months semiannual} & \text{4\%} & \$ 102.95 \\
\text{22 months annual} & \text{6\%} & \$ 107.35 \\
\text{22 months semiannual} & \text{5\%} & \$ 105.45 \\
\end{array}
$$

(i) List the cash flows and cash flow dates for each bond.

(ii) Identify the matrix and the right hand side vector corresponding to the linear system whose solution are the 4 months, 10 months, 16 months, and 22 months discount factors.

(iii) Find the 4 months, 10 months, 16 months, and 22 months discount factors.

## Question 4
Consider three assets with the following expected rates of return, standard deviations of their rates of return, and correlations of their rates of return:

$$
\begin{aligned}
& \mu_{1}=0.1 ; \quad \sigma_{1}=0.15 ; \quad \rho_{1,2}=-0.25 \\
& \mu_{2}=0.15 ; \quad \sigma_{2}=0.3 ; \quad \rho_{2,3}=0.2 ; \\
& \mu_{3}=0.2 ; \quad \sigma_{3}=0.35 ; \quad \rho_{1,3}=0.3
\end{aligned}
$$


(i) Find the covariance matrix $M$ of the rates of return of the three assets.


(ii) A minimum variance portfolio with 16% expected rate of return can be set up by investing a percentage $w_{i}$ of the total value of the portfolio in asset $i$, with $i=1: 3$, where $w_{i}$ can be found by solving the following linear system:

$$
\left(\begin{array}{ccc}
2 M & \mathbf{1} & \mu  \tag{1}\\
\mathbf{1}^{t} & 0 & 0 \\
\mu^{t} & 0 & 0
\end{array}\right)
\left(\begin{array}{c}
w \\
\lambda_{1} \\
\lambda_{2}
\end{array}\right)=\left(\begin{array}{c}
0 \\
1 \\
\mu_{P}
\end{array}\right)
$$

where $\mu_{P}=0.16$,

$$
\mu=\left(\begin{array}{c}
0.1 \\
0.15 \\
0.2
\end{array}\right) \quad \text { and } \quad \mathbf{1}=\left(\begin{array}{l}
1 \\
1 \\
1
\end{array}\right)
$$

The matrices from the $\mathrm{LU}$ decomposition with row pivoting of the matrix on the left hand side of (1) are

$$
\begin{aligned}
P & =\left(\begin{array}{lllll}
0 & 0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 \\
1 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 1
\end{array}\right) ; \\
L & =\left(\begin{array}{ccccc}
1 & 0 & 0 & 0 & 0 \\
-0.0225 & 1 & 0 & 0 & 0 \\
0.0315 & 0.051852 & 1 & 0 & 0 \\
0.045 & -0.333333 & 0.038067 & 1 & 0 \\
0.1 & 0.246914 & 0.400056 & -0.482738 & 1
\end{array}\right) ; \\
U & =\left(\begin{array}{ccccc}
1 & 1 & 1 & 0 & 0 \\
0 & 0.2025 & 0.0645 & 1 & 0.15 \\
0 & 0 & 0.210555 & 0.948148 & 0.192222 \\
0 & 0 & 0 & 1.297240 & 0.142683 \\
0 & 0 & 0 & 0 & -0.045059
\end{array}\right)
\end{aligned}
$$

Find the weights of each asset in this minimum variance portfolio.

(iii) Compute the standard deviation of the returns of the following portfolios with 16% expected rate of return:

1. 30% invested in asset 1, 20% invested in asset 2, 50% invested in asset 3

2. 50% invested in asset 1, 70% invested in asset 3, and short an amount equal to 20% of the value of the portfolio of asset 2


## Eigenvalues and eigenvectors

## Question 1
Let $A$ and $B$ be square matrices of the same size. Show that if $v$ is an eigenvector of both $A$ and $B$, then $v$ is also an eigenvector of the matrix

$$
M=c_{1} A+c_{2} B
$$

where $c_{1}$ and $c_{2}$ are constants. What is the eigenvalue of $M$ corresponding to the eigenvector $v$ ?

## Question 2
Let $A$ be a square matrix such that $A^{2}=A$. Show that any eigenvalue of $A$ is either 0 or 1.

Note: A matrix $A$ with the property that $A^{2}=A$ is called an idempotent matrix.


## Question 3
Let $A$ be a square matrix with the property that there exists a positive integer $n$ such that $A^{n}=0$. Show that any eigenvalue of $A$ must be equal to 0 .

Note: A matrix $A$ with the property that $A^{n}=0$ for a positive integer $n$ is called a nilpotent matrix.


## Question 4

Let $v$ be a column vector of size $n$, and let $A=v v^{t}$ be an $n \times n$ matrix.

(i) How many non-zero eigenvalues does the matrix $A$ have?

(ii) What are the eigenvalues of $A$, and what are the corresponding eigenvectors?

## Question 5

Find the eigenvalues and the eigenvectors of the $n \times n$ matrix

$$
A=\left(\begin{array}{cccc}
d & 1 & \ldots & 1 \\
1 & d & \ldots & 1 \\
\vdots & \vdots & \ddots & \vdots \\
1 & 1 & \ldots & d
\end{array}\right)
$$

where $d \in \mathbb{R}$ is a constant.


## Question 6

Let $\lambda$ and $v$ be an eigenvalue and the corresponding eigenvector of the square matrix $A$ of size $n$. Let $S$ be a nonsingular matrix of size $n$. Show that $\lambda$ is also an eigenvalue of the matrix $S^{-1} A S$. What is the corresponding eigenvector?

## Question 7
Let $A$ be a square matrix with real entries. If $\lambda=a+i b$ is a complex eigenvalue of $A$ (i.e., with $b \neq 0$ ), show that $\bar{\lambda}=a-i b$, the complex conjugate of $\lambda$, is also an eigenvalue of $A$.

## Question 8
Let $A=\left(\begin{array}{cc}-1 & 2 \\ 2 & 2\end{array}\right)$.

(i) Compute the eigenvalues and the eigenvectors of the matrix $A$.

(ii) What is the diagonal form of $A$ ?

(iii) Compute $A^{12}$.

## Question 9

Let $A=\left(\begin{array}{ll}a & b \\ c & d\end{array}\right)$ be a $2 \times 2$ matrix, and let

$$
P_{A}(t)=t^{2}-(a+d) t+(a d-b c)
$$

be the characteristic polynomial associated to $A$.

Show that $P_A(A) = 0$, i.e., show that

$$ A^2 - (a+d)A + (ad-bc)I = 0$$

Note: This is the $2 \times 2$ case of the Cayley-Hamilton theorem which states that $P_A(A) = 0$ for any square matrix $A$.

## Question 10
Let $A$ be an $n \times n$ matrix given by

$$
\begin{aligned}
A(i, i) & =2, \forall i=1: n \\
A(i, i-1) & =1, \forall i=2: n \\
A(j, k) & =0, \text { otherwise. }
\end{aligned}
$$

Find the eigenvalues and the eigenvectors of $A$.


## Question 11

(i) Show that the eigenvalues of the matrix

$$
A=\left(\begin{array}{cccc}
-16 & 6 & -6 & 0 \\
-30 & 11 & -12 & 0 \\
15 & -6 & 5 & 0 \\
0 & 0 & 0 & -1
\end{array}\right)
$$

are -1 , with multiplicity 3 , and 2 , with multiplicity 1 .

Show that $\left(\begin{array}{c}0 \\ 1 \\ 1 \\ -2\end{array}\right),\left(\begin{array}{c}2 \\ 2 \\ -3 \\ 3\end{array}\right),\left(\begin{array}{l}0 \\ 0 \\ 0 \\ 1\end{array}\right)$ are three linearly independent eigenvectors corresponding to the eigenvalue -1 , and show that there exists only one linearly independent eigenvector of the matrix $A$ corresponding to the eigenvalue 2 , e.g., $\left(\begin{array}{c}1 \\ 2 \\ -1 \\ 0\end{array}\right)$.


(ii) Show that the eigenvalues of the matrix

$$
B=\left(\begin{array}{cccc}
10 & -20 & -32 & -26 \\
18 & -41 & -68 & -54 \\
-14 & 19 & 26 & 23 \\
7 & 1 & 9 & 4
\end{array}\right)
$$

are -1 , with multiplicity 3 , and 2 , with multiplicity 1 .

Show that there exists only one linearly independent eigenvector of the matrix $B$ corresponding to the eigenvalue -1 , e.g., $\left(\begin{array}{c}0 \\ -1 \\ -1 \\ 2\end{array}\right)$, and show that $\left(\begin{array}{c}1 \\ 2 \\ -1 \\ 0\end{array}\right)$ is an eigenvector corresponding to the eigenvalue 2 .

In [ ]:
import numpy as np
import copy
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))
from nla import func # my own package based on previous homeworks

def lu_row_pivoting(A): #@save
    """
    LU decomposition with row pivoting
    input: A
    output: P, L, U
    """
    AA = copy.deepcopy(A)
    n = AA.shape[0]
    # initialize
    P, L = np.eye(n), np.eye(n)
    U = np.eye(n)
    for i in range(0, n-1):
        i_max = np.argmax(np.abs(AA[i:n, i])) + i
        # switch rows i and i_max of A
        vv = copy.deepcopy(AA[i, i:n])
        AA[i, i:n] = AA[i_max, i:n]
        AA[i_max, i:n] = vv
        # update matrix P
        cc = copy.deepcopy(P[i])
        P[i] = P[i_max]
        P[i_max] = cc
        if i > 0:
            ww = copy.deepcopy(L[i, 0:i])
            L[i, 0:i] = L[i_max, 0:i]
            L[i_max, 0:i] = ww
        for j in range(i, n):
            L[j, i] = AA[j, i] / AA[i, i]
            U[i, j] = AA[i, j]
        for j in range(i+1, n):
            for k in range(i+1, n):
                AA[j, k] -= L[j, i] * U[i, k]
    L[n-1, n-1] = 1
    U[n-1, n-1] = AA[n-1, n-1]
    return P, L, U

In [159]:
def linear_solve_lu_row_pivoting(A, b):
    """
    Linear solver using LU decomposition with row pivoting
    input: A, b
    output: x
    """
    P, L, U = lu_row_pivoting(A)
    y = func.forward_subset(L, P@b)
    x = func.backward_subset(U, y)
    return x

In [138]:
A = np.array([
    [2,-1,0,1],
    [-2,0,1,-1],
    [4,-1,0,1],
    [4,-3,0,2]
])

In [134]:
A = np.array([
    [1,2,-7,-1.5,2],
    [4,4,0,-6,-2],
    [-2,-1,2,6,2.5],
    [0,-2,2,-4,1],
    [2,1,13,-5,3.5]
])

In [186]:
A = np.array([
    [2,1,1],
    [4,1,0],
    [-2,2,1]
])

In [187]:
P,L,U=lu_row_pivoting(A)

In [188]:
L

array([[ 1.,  0.,  0.],
       [ 2.,  1.,  0.],
       [-1., -3.,  1.]])

In [176]:
P@A==L@U

array([[ True,  True,  True],
       [ True, False,  True],
       [ True, False,  True]])

In [173]:
A = np.array([
    [2,102,0,0],
    [5,0,105,0],
    [1.5,1.5,1.5,101.5],
    [0,6,0,106]
])

b = np.array(
    [101.5,105.5,101,106.75]
)
linear_solve_lu_row_pivoting(A,b)

[np.float64(0.991637),
 np.float64(0.975654),
 np.float64(0.957541),
 np.float64(0.95185)]

In [149]:
AA = copy.deepcopy(A)
n = AA.shape[0]
# initialize
P, L = np.eye(n), np.eye(n)
U = np.eye(n)

In [152]:
i=1
i_max = np.argmax(np.abs(AA[i:n, i])) + i
# switch rows i and i_max of A
vv = copy.deepcopy(AA[i, i:n])
AA[i, i:n] = AA[i_max, i:n]
AA[i_max, i:n] = vv
# update matrix P
cc = copy.deepcopy(P[i])
P[i] = P[i_max]
P[i_max] = cc
if i > 0:
    ww = copy.deepcopy(L[i, 0:i])
    L[i, 0:i] = L[i_max, 0:i]
    L[i_max, 0:i] = ww
for j in range(i, n):
    L[j, i] = AA[j, i] / AA[i, i]
    U[i, j] = AA[i, j]
for j in range(i+1, n):
    for k in range(i+1, n):
        AA[j, k] -= L[j, i] * U[i, k]

In [157]:
AA

array([[ 4,  0,  1],
       [-2,  1,  3],
       [ 2, -1,  3]])

In [189]:
theta = np.array([
    [5000,400,-100]
])
B = np.array([
    [1,1,1,1],
    [22,22,18,18],
    [32,28,32,28]
])
theta@B

array([[10600, 11000,  9000,  9400]])